### ISSUE TITLE
Further enhance the ProjectQ backend

### ISSUE THREAD

**Issue by diego-plan9** [QISKit/qiskit-core#207]
After the merge of #138, the backend interface to ProjectQ has made it into the SDK, although a number of optimizations and refining has been suggested and discussed throughout the life of the PR. 

This issue is mostly for keeping track of the conversation and ensuring they are followed up, in the hopes of reaching a smoother ProjectQ backend integration. It would be recommended to revise the full comments of the PR for a better glance of the issues, but in particular:

 * Ideas for improving the perfomance can be found at https://github.com/QISKit/qiskit-sdk-py/pull/138#pullrequestreview-82365987
* A way of setting a custom single qubit matrix was discussed at https://github.com/QISKit/qiskit-sdk-py/pull/138#pullrequestreview-82431306

**Comment by ajavadia** [comment]
closing this and opening issue in its own repository.
https://github.com/QISKit/qiskit-addon-projectq/issues/7
