### ISSUE TITLE
QISKit 0.5 status and notes

### ISSUE THREAD

**Issue by jaygambetta** [QISKit/qiskit-core#413]
posting this to the public so the the community can see what we want in 0.5

- [ ] 1st —  `backend_rework` branch*
#376: merged
At the end of this level 2 user will be happy with no quantumprgroam and will use qiskit.execute
   - [x] move the auto naming in `create_quantum_register, create_classical_register` to `QuantumRegister, ClassicalRegister` creation
   - [x] add auto naming for `QuantumCircuit` creation
   - [x] finish `qiskit.compile()` function level 1 user 
   - [x] finish `qiskit.execute()` function level 2 user
   - [x] update README and `using_qiskit`, `hello_quantum` examples. I want to have a hello world, and `using_qiskit_level_0` (execute), `using_qiskit_level_1` (compile and run on backends) and `using_qiskit_level_2` (future pass manager and DAG compiling)
   - [x] tests and passing old ones
   - [x] check backward compatibility of quantum program
   - [x] can openquantumcompiler be removed here
   - [x] a new backend_manager (old backendutils) with a register
   - [x] can backendutils be removed here
   - [ ] update the documentation with qiskit.compile and qiskit.execute
   - [x] register('token', url)
   - [x] backends (filter)
   - [x] all_backends()
   - [x] backend.configuration schema
   - [x] backend.status schema
   - [x] merge

- [x]  `cpp-simulator-refactor` branch*
#386: merged - for the C++ changes
#421: closed - for the backend naming changes (reissued in #435)
#435: merged
   - [x] Treat `snapshot`, `noise`, `load`, `save` as barriers in the mapper, so they don’t move around.
   - [x] Subclass statevector simulator from qasm simulator (python and cpp)
   - [x] Tests
   - [x] making sure naming conventions is correct and local_qasm_simulator defualts to c++
   - [x] update the documentation with how to use the different simulators 
   - [x] merge

- [ ] Generate new qobj format*
#415: open
#376: closed (added schemas into the codebase)
   - [ ] Generate them according to schemas and edit schemas appropriately 
   - [ ] Also make sure it is forward compatible with pulse (see document)
   - [ ] update the documentation to explain the qobj
   - [ ] merge

- [ ]  Qobj object and validate against schemas
#415: open
#144: closed (introduced in #415)
   - [ ] create a Qobj object
   - [ ] make sure all backends are using qobj and that they pass the schema
   - [ ] in the document make sure it make sense
   - [ ] check that the exp is working with this format
   - [ ] CONFIRM THAT WE HAVE FIXED THE ORDERING BUG
   - [ ] merge

- [ ] run Qobj and return instead of QuantumJob
#415: open
#326: closed (closed and introduced in #415)
   - [ ] update using_qiskit_level_2
   - [ ] can QuantumJob be removed here
   - [ ] update any documentation
   - [ ] merge

- [ ] Result object
  - [ ] remove qobj

- [ ]  Introduce a Job object and make all runs async
#403: merged
At the end of this level 1 user will be happy with no quantumprgroam and they have control of their jobs
   - [x] create a Job Object
   - [ ] update using_qiskit_level_2
   - [ ] job = backend.run(qobj) where qobj is dict or object
   - [x] job.done
   - [x] job.status
   - [x] job.cancel
   - [x] job.result()
   - [x] job.job_id (IBM Q)
   - [ ] shows examples of how users can get the status and cancel a job
   - [ ] make sure quantumprogram still works
   - [ ] merge
- [ ] backend
   - [ ] backend.jobs()
   - [ ] backend.retrieve_job(job_id)
   - [x] backend.status
   - [ ] backend.schema
   - [x] backend.configuration
   - [ ] backend.properties
   - [ ] update the documentation with backend uses
 
- [ ]  remove sympy backends and projectq backends and provided them as qiskit-core-backend-plugins example
   - [ ] sympy
   - [ ] projectq

- [ ] Qconfig
   - [ ] provide a simple solution
   - [ ] merge

- [ ] parameters and calibrations go to properties and pass a schema

*After the release*
- [ ] backend.validation
- [ ] Remove QuantumJob as qobj should have replaced it
- [x] Remove JobProcessor as it should be replaced with JobProcessor of the actual Job object.
- [x] remove opencompiler as it should be obsolete
- [ ] clean ibmq provider
- [ ] start to get errors and checks against the schema in place.

Lets add below anything i forgot. 

Also @ajavadia when we are finished with the spec for qobj can we add a link to this in the comments. Also @ewinston @diego-plan9 @ajavadia lets link pr's against this.

**Comment by yehuda-naveh** [comment]
Hi @jaygambetta can we help on any of these? e.g., with the qobj items, or the sympy/projectq/qconfig? we can be free for that starting Sunday

**Comment by jaygambetta** [comment]
@yehuda-naveh great. @ajavadia and @ewinston and @diego-plan9 can you let @yehuda-naveh know which parts they can help out on.

**Comment by yehuda-naveh** [comment]
@diego-plan9 @ajavadia  will you be our contact on this? We'd be happy to help for 0.5 with the qobj items, or the sympy/projectq/qconfig, or elsewhere. Need your confirm, and initial pointer to discussion. Otherwise, we'd just continue our WIP on operator-sum and noise approximations

**Comment by yehuda-naveh** [comment]
@yaelbh, after discussing with @jaygambetta, let's start with the projectq item

**Comment by yehuda-naveh** [comment]
Thanks @ajavadia . We're looking into both.

**Comment by yaelbh** [comment]
I've opened Issue #425 for the ProjectQ item and Issue #426 for the test-across-backends item.

**Comment by atilag** [comment]
0.5 was released some time ago. Shall we close this issue @jaygambetta ?

**Comment by jaygambetta** [comment]
I would rather rename it 0.6 or move the things we did not get done into 0.6 so we keep track of them.

**Comment by diego-plan9** [comment]
I have made an effort to move each individual checklist (the ones that still had open items) into single issues, labeled with `type: meta`:
https://github.com/QISKit/qiskit-core/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+meta%22

and set them for the next milestone:
https://github.com/QISKit/qiskit-core/milestone/2

I did not transfer all the items directly trying to reflect the current status and the pending items - please feel free to add more items to the existing issues, open new ones, or comment as much as possible!
