### ISSUE TITLE
Use `math.pi` and other constants instead of numeric in QASM

### ISSUE THREAD

**Issue by rraymondhp** [QISKit/qiskit-core#432]
I failed to run some circuits due to characters limitation of QASM. I think the number of characters can be significantly reduced if the QASM file generated use `math.pi` instead of numerical values as below:
```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[8];
creg ans[3];
u2(0,3.14159265358979) q[7];
u3(3.14159265358979,0,3.14159265358979) q[3];
u2(0,3.14159265358979) q[2];
u2(0,3.14159265358979) q[1];
u2(0,3.14159265358979) q[0];
cx q[6],q[7];
cx q[3],q[4];
cx q[1],q[0];
u2(0,3.14159265358979) q[7];
u2(0,3.14159265358979) q[6];
cx q[6],q[7];
u2(0,3.14159265358979) q[7];
u2(0,3.14159265358979) q[6];
cx q[6],q[7];
cx q[6],q[5];
u2(0,3.14159265358979) q[7];
u2(0,3.14159265358979) q[5];
u2(0,3.14159265358979) q[6];
``` 
## Expected Behavior

The value `3.14...` and its derivatives can be compactly described with `math.pi`. QASM spec mentions that it understands the definition of `math.pi`. The generated QASM file should use `math.pi` instead of the numeric values.  

## Current Behavior

`3.14..` is used instead of `math.pi`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 3.6.1):
* Operating System and version:

**Comment by 1ucian0** [comment]
The QASM specification allows the use of `pi`.

**Comment by rraymondhp** [comment]
Yes, but the compiled circuits seem never use `pi`, although I wrote the circuit using `pi`.

**Comment by rraymondhp** [comment]
Thanks. Here is a notebook that was used to find that `3.14..` were generated in QASM. 

https://github.com/rraymondhp/qiskit-tutorial/blob/4f5e5c3f6786719ee6ef47e45d889093f9c1e472/reference/algorithms/grover_algorithm.ipynb

I found that by using `pi`, the number of chars is reduced to 40k (from 60k+).

**Comment by jaygambetta** [comment]
This is not a qiskit issue the real issue is in the backend which we are working on getting better estimates of the length and moving away from cloud choices that limited the size of the file.

**Comment by ajavadia** [comment]
Closing since this is being worked on at API level. Qobj will also reduce backend size quite a bit by removing the qasm.
