### ISSUE TITLE
Provide a mechanism to provide the QISKit API token at runtime

### ISSUE THREAD

**Issue by tellison** [QISKit/qiskit-core#471]
At present it is necessary to modify the `QConfig.py` file to [hard code the `APItoken` variable definition](https://github.com/QISKit/qiskit-sdk-py/blob/master/Qconfig.py.default#L6).

In environments where it is not easy/possible to modify files in the QISKit installation location, and

1. it is not desirable to store a particular API token in plain sight, and
1. it is desirable to support multiple API users,

there should be a way to pass in the `APItoken` value at runtime.

A suggested way to do this is through an environment variable.

**Comment by diego-plan9** [comment]
Thanks @tellison - we have a revamp of the `Qconfig` system planned, as a more flexible system is a rather demanded feature (there is a discussion at #385 and previously #226). Unfortunately it was not ready by the time of the latest 0.5 release, but hopefully we will retake the work on that feature shortly and it will include more streamlined support for environment variables and flexibility: in the meantime, as you suggested, a workaround is using custom code in `Qconfig.py` for tailoring it to your needs.

**Comment by diego-plan9** [comment]
Closing this issue in the hopes of continuing the discussion at #540 and finally get the feature in place :tada:
