### ISSUE TITLE
Undefined variable in documentation when getting results from real chips (backends)

### ISSUE THREAD

**Issue by cbjuan** [QISKit/qiskit-core#570]
### Informations

- **QISKit (Python SDK) version**: 0.5.4
- **Python version**: 3.6
- **Operating system**: OSX

### What is the current behavior?
In the documentation related to [Quantum chips](https://www.qiskit.org/documentation/quickstart.html#quantum-chips), there is an error in the variable used to get the results achieved using a real (or an online) backend. That variable has not been defined previously in the code.

### Steps to reproduce the problem
The errors are in the file https://github.com/QISKit/qiskit-core/blob/master/doc/example_real_backend.rst In that file, appears two times the following:
```
# Compile and run the Quantum Program on a real device backend
job_exp = execute(qc, 'ibmqx4', shots=1024, max_credits=10)
result = job.result()
```
and should be:

```
# Compile and run the Quantum Program on a real device backend
job_exp = execute(qc, 'ibmqx4', shots=1024, max_credits=10)
result = job_exp.result()
```

### What is the expected behavior?
In the documentation should be used a previously defined variable (`job_exp`)

### Suggested solutions
I'm opening a PR with the solution described above.

**Comment by ajavadia** [comment]
Fixed by #571.
Thanks @cbjuan for both reporting and fixing.
