### ISSUE TITLE
Bug in circuit addition

### ISSUE THREAD

**Issue by rraymondhp** [QISKit/qiskit-core#572]
### Informations

- **QISKit (Python SDK) version**: 0.5.4
- **Python version**: 3.6.5
- **Operating system**: MacOSX

### What is the current behavior?
Circuit addition involving the inverse of circuit/composite gate does not work. 

### Steps to reproduce the problem
`circuit_drawer(circs["PROTOZOAN"])`
![image](https://user-images.githubusercontent.com/15240898/41490313-6db50706-712e-11e8-94eb-8b07f35683b6.png)

`circuit_drawer(circs["YEAST"])`
![image](https://user-images.githubusercontent.com/15240898/41490334-87fd1356-712e-11e8-95af-7537a7c2b19a.png)

`circuit_drawer(inverse_circs["YEAST"])`
![image](https://user-images.githubusercontent.com/15240898/41490345-94a2b264-712e-11e8-9389-e8d111f3293c.png)

`circuit_drawer(circs["PROTOZOAN"] + inverse_circs["YEAST"])`
![image](https://user-images.githubusercontent.com/15240898/41490353-a1e84042-712e-11e8-8236-282728b46fa7.png)

### What is the expected behavior?
Addition/appending circuits.

### Suggested solutions
Dunno.

**Comment by ajavadia** [comment]
@rraymondhp I can't reproduce this issue from circuit pictures. Can you paste the code to generate those circuits? I think they were generated with the `initialize` command.

**Comment by ajavadia** [comment]
@rraymondhp thanks. I found the issue. I will put in a fix.
