### ISSUE TITLE
Visualizing Circuits error: `Poppler` installation

### ISSUE THREAD

**Issue by mathophilic** [QISKit/qiskit-core#586]
I have just started using Qiskit Tutorials> Getting Started With Qiskit > Write and run your first quantum program ([HERE](https://github.com/QISKit/qiskit-tutorial/blob/master/reference/tools/getting_started.ipynb)).

I have been able to connect to my IBM Q experience (using token), but I got stock in the "Visualize Circuit" part. The error is: 

"WARNING:qiskit.tools.visualization:WARNING: Unable to convert pdf to image. Is `poppler` installed? Skipping circuit drawing..."

To fix this I installed poppler on MikTex (it was actually installed itself but I removed it and installed it again in case.). 

I would very much appreciate any helps to fix this error.

**Comment by attp** [comment]
As described in the [tutorial install](https://github.com/QISKit/qiskit-tutorial/blob/master/INSTALL.md), as well as installing `poppler`, you need to add it to your `PATH` (I'm assuming you are working on a Windows machine):

- Install [MiKTeX](https://miktex.org/download).
- Install Poppler:
    - Download the [latest binary](http://blog.alivate.com.au/wp-content/uploads/2017/01/poppler-0.51_x86.7z).
    - Extract the downloaded `.7z` file into user directory: `c:\Users\<user_name>`\. Note: You will need to have the[ 7zip software](https://www.7-zip.org/download.html) for this.
    - Add to PATH:
        - Right click on "This PC" -> Properties -> Advanced System Settings -> Environment Variables
        - Add `C:\Users\<user_name>\poppler-0.51\bin` to the user's path.

**Comment by mathophilic** [comment]
Thanks (and yes, I'm using Windows). I did that, and that error is fixed now. But now, it shows the following error:

"WARNING:qiskit.tools.visualization:WARNING: Unable to compile latex. Is `pdflatex` installed? Skipping circuit drawing..."

(I'm sorry if my question seems naive but I'm a beginner.)

**Comment by ajavadia** [comment]
@mathophilic can you follow the instructions in section 5 here:
https://github.com/QISKit/qiskit-tutorial/blob/master/INSTALL.md

also what OS do you have?

We will soon have another method for circuit visualization which doesn't require Latex/Poppler (#579).

**Comment by mathophilic** [comment]
@ajavadia, Thanks. My OS is Windows 10 Home. I did follow those instructions on section 5 as @attp also mentioned, and it solved the first error which was for poppler. However, now it seemingly does not compile latex, which is weird since I use latex all the time on my computer for my papers etc. (I mean I have MikTex installed but it still doesn't work fine on Jupyter notebook.)

**Comment by mathophilic** [comment]
Is it a possibility that the problem is that MikTex is installed in AppData directory rather than program files?

**Comment by ajavadia** [comment]
I am not sure. Tagging @alfrisch here since he is the only Windows user that I know who successfully got this to work.

**Comment by rraymondhp** [comment]
Not a solution, but you may want to consider using Binder:
https://mybinder.org/v2/gh/QISKit/qiskit-tutorial/master?filepath=index.ipynb

**Comment by mathophilic** [comment]
Thanks everybody for the help. My professor found one way out. Maybe not the best. I'm putting it here for if someone had the same issue in future:
_Explanation_:  pdflatex in MikTex converts the code to pdf and pdftocairo.exe which is in the poppler file is the program that converts pdf to image, and this image is the one shown on the screen. Clearly, the problem was from the function circuit_drawer() in the visualization.py file. (Seemingly, the problem came from the way this function referenced directories.) This file for me was located at this directory: `C:\Users\<username>\Miniconda3\envs\QISKitenv\Lib\site-packages\qiskit\tools`. 

_The change_: We changed the following part of the code (the part corresponding to the poppler error):
` try:
                current=os.getcwd()
                os.chdir(tmpdirname)
                subprocess.run(["pdftocairo", "-singlefile", "-png", "-q",
                                filename+ '.pdf', filename])
                im = Image.open("{0}.png".format(filename))
                im = trim(im)
                os.remove("{0}.png".format(filename))
                os.chdir(current)
            except OSError as e:
                if e.errno == os.errno.ENOENT:
                    logger.warning('WARNING: Unable to convert pdf to image. '
                                   'Is `poppler` installed? '
                                   'Skipping circuit drawing...')
                else:`

**Comment by ajavadia** [comment]
@mathophilic can you please tell me what version of QISKit you are using?
If you used pip, you can check it by: `pip show qiskit`

**Comment by mathophilic** [comment]
Sure @ajavadia. Version 0.5.3

**Comment by ajavadia** [comment]
@mathophilic oh, this was fixed in 0.5.4. Please upgrade.

Sorry, for some reason i thought you have the latest version. Should have suggested that first.

**Comment by ajavadia** [comment]
So this seems resolved. I am closing, feel free to open if you continue having problems.
