### ISSUE TITLE
Finding the result of the action of the identity operator on |0>

### ISSUE THREAD

**Issue by mathophilic** [QISKit/qiskit-core#596]
My QISKit version is 0.5.4 (the latest I believe), and I have python 3.7 on Windows 10 OS. 

I wanted to find the output of the action of identity operator on the qubit |0> as a baby test. I was expecting the output to be again |0>, while the output was indeed:  `{'statevector': array([7.07106781e-01+0.j , 4.32978028e-17+0.70710678j])}` . I used the following sets of commands: `q = QuantumRegister(1)` `qc = QuantumCircuit(q)` `job = execute(qc, backend='local_statevector_simulator')` `job.result().get_data(qc)`. 

(The set up is basically from [THIS ](https://nbviewer.jupyter.org/github/QISKit/qiskit-tutorial/blob/master/reference/tools/quantum_gates_and_linear_algebra.ipynb#Identity-gate)page of the tutorial.) 

What am I doing wrong?

**Comment by ajavadia** [comment]
The commands you have written are for an empty circuit. You need to add at least one gate.
You can add the identity gate as `iden`.
The code below works:
```python
from qiskit import *
q = QuantumRegister(1)
qc = QuantumCircuit(q)
qc.iden(q)
job = execute(qc, backend='local_statevector_simulator')
job.result().get_statevector()   # job.result().get_data(qc) also works
```
